[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "scrubssh"
version = "0.1.0"
description = "Python CLI tool to inspect, filter, and clean SSH known_hosts entries (optimized for HackTheBox workflows)."
requires-python = ">=3.8"
readme = "README.md"
license = { text = "MIT" }

[project.scripts]
scrub_ssh = "scrubssh.cli:main"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

